name: Qodana
on:
  workflow_dispatch:
  push:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 8
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Cache Gradlew packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1.5
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
